-- V1 - Schema base compatível com H2 em MODE=MSSQLServer

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula VARCHAR(30) NOT NULL UNIQUE,
    nome_exibicao VARCHAR(120),
    senha_hash VARCHAR(128) NOT NULL,
    senha_salt VARCHAR(64) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    primeiro_acesso BOOLEAN NOT NULL DEFAULT TRUE,
    data_criacao TIMESTAMP NOT NULL,
    ultimo_acesso TIMESTAMP
);

CREATE TABLE IF NOT EXISTS preferencias_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE,
    tema VARCHAR(30) NOT NULL DEFAULT 'PADRAO',
    menu_compacto BOOLEAN NOT NULL DEFAULT FALSE,
    ultima_rota VARCHAR(120),
    atualizado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_preferencias_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS servicos_internos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    titulo VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    categoria VARCHAR(80) NOT NULL,
    rota_frontend VARCHAR(150),
    icone VARCHAR(80),
    ordem INT NOT NULL DEFAULT 0,
    destaque BOOLEAN NOT NULL DEFAULT FALSE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS conteudos_internos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(60) NOT NULL UNIQUE,
    titulo VARCHAR(150) NOT NULL,
    subtitulo VARCHAR(200),
    descricao CLOB,
    tipo VARCHAR(40) NOT NULL,
    slug VARCHAR(120),
    ordem INT NOT NULL DEFAULT 0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS acessos_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    servico_id BIGINT NOT NULL,
    quantidade_acessos INT NOT NULL DEFAULT 0,
    ultimo_acesso TIMESTAMP NOT NULL,
    CONSTRAINT fk_acessos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_acessos_servico FOREIGN KEY (servico_id) REFERENCES servicos_internos(id),
    CONSTRAINT uk_acesso_usuario_servico UNIQUE (usuario_id, servico_id)
);

CREATE TABLE IF NOT EXISTS auditoria_acessos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    matricula VARCHAR(30),
    acao VARCHAR(50) NOT NULL,
    referencia VARCHAR(120),
    descricao VARCHAR(500),
    criado_em TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_usuarios_matricula ON usuarios(matricula);
CREATE INDEX IF NOT EXISTS ix_acessos_usuario ON acessos_servico(usuario_id);
CREATE INDEX IF NOT EXISTS ix_auditoria_usuario ON auditoria_acessos(usuario_id);
