-- V3 - Adequação portal compatível com H2

CREATE TABLE IF NOT EXISTS favoritos_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    servico_id BIGINT NOT NULL,
    titulo_customizado VARCHAR(120),
    observacao VARCHAR(500),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_criacao TIMESTAMP NOT NULL,
    CONSTRAINT fk_favoritos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_favoritos_servico FOREIGN KEY (servico_id) REFERENCES servicos_internos(id),
    CONSTRAINT uk_favorito_usuario_servico UNIQUE (usuario_id, servico_id)
);

CREATE TABLE IF NOT EXISTS sistemas_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    url VARCHAR(300),
    categoria VARCHAR(80),
    icone VARCHAR(80),
    favorito BOOLEAN NOT NULL DEFAULT FALSE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_criacao TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP,
    CONSTRAINT fk_sistemas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS anotacoes_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    titulo VARCHAR(120) NOT NULL,
    descricao CLOB,
    referencia VARCHAR(120),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_criacao TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP,
    CONSTRAINT fk_anotacoes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS processos_internos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL UNIQUE,
    titulo VARCHAR(150) NOT NULL,
    descricao CLOB,
    categoria VARCHAR(80),
    rota_frontend VARCHAR(150),
    icone VARCHAR(80),
    ordem INT NOT NULL DEFAULT 0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS checklist_processo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processo_id BIGINT NOT NULL,
    descricao VARCHAR(400) NOT NULL,
    ordem INT NOT NULL DEFAULT 0,
    obrigatorio BOOLEAN NOT NULL DEFAULT TRUE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_checklist_processo FOREIGN KEY (processo_id) REFERENCES processos_internos(id)
);

CREATE TABLE IF NOT EXISTS usuario_checklist_processo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    checklist_id BIGINT NOT NULL,
    concluido BOOLEAN NOT NULL DEFAULT FALSE,
    data_conclusao TIMESTAMP,
    CONSTRAINT fk_usuario_checklist_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_usuario_checklist_item FOREIGN KEY (checklist_id) REFERENCES checklist_processo(id),
    CONSTRAINT uk_usuario_checklist UNIQUE (usuario_id, checklist_id)
);

CREATE INDEX IF NOT EXISTS ix_favoritos_usuario ON favoritos_usuario(usuario_id);
CREATE INDEX IF NOT EXISTS ix_sistemas_usuario ON sistemas_usuario(usuario_id);
CREATE INDEX IF NOT EXISTS ix_anotacoes_usuario ON anotacoes_usuario(usuario_id);
CREATE INDEX IF NOT EXISTS ix_processos_categoria ON processos_internos(categoria);
CREATE INDEX IF NOT EXISTS ix_checklist_processo ON checklist_processo(processo_id);

INSERT INTO servicos_internos (codigo, titulo, descricao, categoria, rota_frontend, icone, ordem, destaque, ativo)
SELECT 'ABERTURA_CONTA', 'Abertura de Conta', 'Orientações e pré-acessos para abertura de conta.', 'ATENDIMENTO', '/processos/abertura-conta', 'file-check', 10, TRUE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM servicos_internos WHERE codigo = 'ABERTURA_CONTA');

INSERT INTO servicos_internos (codigo, titulo, descricao, categoria, rota_frontend, icone, ordem, destaque, ativo)
SELECT 'HABITACAO', 'Habitação', 'Acesso rápido aos fluxos e sistemas de habitação.', 'NEGOCIOS', '/servicos/habitacao', 'home', 20, TRUE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM servicos_internos WHERE codigo = 'HABITACAO');

INSERT INTO servicos_internos (codigo, titulo, descricao, categoria, rota_frontend, icone, ordem, destaque, ativo)
SELECT 'COBRANCA', 'Cobrança', 'Atalhos de consulta e orientação para cobrança.', 'NEGOCIOS', '/servicos/cobranca', 'receipt', 30, TRUE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM servicos_internos WHERE codigo = 'COBRANCA');

INSERT INTO servicos_internos (codigo, titulo, descricao, categoria, rota_frontend, icone, ordem, destaque, ativo)
SELECT 'JURIDICO', 'Jurídico', 'Consulta a orientações, normativos e fluxos jurídicos.', 'SUPORTE', '/servicos/juridico', 'scale', 40, TRUE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM servicos_internos WHERE codigo = 'JURIDICO');

INSERT INTO conteudos_internos (codigo, titulo, subtitulo, descricao, tipo, slug, ordem, ativo)
SELECT 'NORM_ABERTURA_CONTA', 'Normativo de Abertura de Conta', 'Consulta rápida', 'Regras operacionais e orientações resumidas para abertura de conta.', 'NORMATIVO', 'normativo-abertura-conta', 10, TRUE
WHERE NOT EXISTS (SELECT 1 FROM conteudos_internos WHERE codigo = 'NORM_ABERTURA_CONTA');

INSERT INTO conteudos_internos (codigo, titulo, subtitulo, descricao, tipo, slug, ordem, ativo)
SELECT 'NORM_COTACOES', 'Normativo de Cotações e Propostas', 'Agência', 'Orientações para acompanhamento de cotações, propostas e pendências da agência.', 'NORMATIVO', 'normativo-cotacoes-propostas', 20, TRUE
WHERE NOT EXISTS (SELECT 1 FROM conteudos_internos WHERE codigo = 'NORM_COTACOES');

INSERT INTO processos_internos (codigo, titulo, descricao, categoria, rota_frontend, icone, ordem, ativo)
SELECT 'ABERTURA_CONTA', 'Abertura de Conta - Orientações de Pré-Acesso',
       'Fluxo de apoio com documentação necessária, conferência e pontos de atenção antes de iniciar a abertura de conta.',
       'ATENDIMENTO', '/processos/abertura-conta', 'file-check', 1, TRUE
WHERE NOT EXISTS (SELECT 1 FROM processos_internos WHERE codigo = 'ABERTURA_CONTA');

INSERT INTO checklist_processo (processo_id, descricao, ordem, obrigatorio, ativo)
SELECT p.id, 'Conferir documento oficial com foto do cliente.', 1, TRUE, TRUE
FROM processos_internos p
WHERE p.codigo = 'ABERTURA_CONTA'
  AND NOT EXISTS (SELECT 1 FROM checklist_processo c WHERE c.processo_id = p.id AND c.ordem = 1);

INSERT INTO checklist_processo (processo_id, descricao, ordem, obrigatorio, ativo)
SELECT p.id, 'Validar CPF e dados cadastrais antes de prosseguir.', 2, TRUE, TRUE
FROM processos_internos p
WHERE p.codigo = 'ABERTURA_CONTA'
  AND NOT EXISTS (SELECT 1 FROM checklist_processo c WHERE c.processo_id = p.id AND c.ordem = 2);

INSERT INTO checklist_processo (processo_id, descricao, ordem, obrigatorio, ativo)
SELECT p.id, 'Confirmar comprovante de residência quando aplicável.', 3, TRUE, TRUE
FROM processos_internos p
WHERE p.codigo = 'ABERTURA_CONTA'
  AND NOT EXISTS (SELECT 1 FROM checklist_processo c WHERE c.processo_id = p.id AND c.ordem = 3);

INSERT INTO checklist_processo (processo_id, descricao, ordem, obrigatorio, ativo)
SELECT p.id, 'Selecionar o canal/sistema correto para abertura de conta.', 4, TRUE, TRUE
FROM processos_internos p
WHERE p.codigo = 'ABERTURA_CONTA'
  AND NOT EXISTS (SELECT 1 FROM checklist_processo c WHERE c.processo_id = p.id AND c.ordem = 4);
