-- V4 - Cotações e propostas compatível com H2

CREATE TABLE IF NOT EXISTS cotacoes_propostas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(40) NOT NULL UNIQUE,
    agencia VARCHAR(20) NOT NULL,
    nome_cliente VARCHAR(160) NOT NULL,
    cpf_cnpj VARCHAR(20),
    produto VARCHAR(120) NOT NULL,
    modalidade VARCHAR(120),
    valor DECIMAL(15,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    prioridade VARCHAR(20) NOT NULL DEFAULT 'MEDIA',
    responsavel VARCHAR(120) NOT NULL,
    matricula_responsavel VARCHAR(30),
    data_criacao TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP NOT NULL,
    prazo_resposta DATE,
    observacao VARCHAR(1000),
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS historico_proposta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposta_id BIGINT NOT NULL,
    status_anterior VARCHAR(30),
    status_novo VARCHAR(30) NOT NULL,
    usuario VARCHAR(120) NOT NULL,
    matricula_usuario VARCHAR(30),
    descricao VARCHAR(500),
    criado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_historico_proposta FOREIGN KEY (proposta_id) REFERENCES cotacoes_propostas(id)
);

CREATE TABLE IF NOT EXISTS comentarios_proposta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposta_id BIGINT NOT NULL,
    autor VARCHAR(120) NOT NULL,
    matricula_autor VARCHAR(30),
    comentario VARCHAR(1000) NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_comentario_proposta FOREIGN KEY (proposta_id) REFERENCES cotacoes_propostas(id)
);

CREATE INDEX IF NOT EXISTS ix_cotacoes_status ON cotacoes_propostas(status);
CREATE INDEX IF NOT EXISTS ix_cotacoes_agencia ON cotacoes_propostas(agencia);
CREATE INDEX IF NOT EXISTS ix_cotacoes_cliente ON cotacoes_propostas(nome_cliente);
CREATE INDEX IF NOT EXISTS ix_historico_proposta ON historico_proposta(proposta_id);
CREATE INDEX IF NOT EXISTS ix_comentarios_proposta ON comentarios_proposta(proposta_id);

INSERT INTO cotacoes_propostas (
    numero, agencia, nome_cliente, cpf_cnpj, produto, modalidade, valor, status, prioridade,
    responsavel, matricula_responsavel, data_criacao, data_atualizacao, prazo_resposta, observacao, ativo
)
SELECT 'PROP-2026-0001', '1234', 'Cliente Demonstração 01', '00000000000', 'Abertura de Conta', 'Conta Pessoa Física',
       0.00, 'EM_ANALISE', 'MEDIA', 'Atendente Agência', 'C000001',
       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, DATEADD('DAY', 2, CURRENT_DATE),
       'Registro inicial para demonstrar a tela de cotações e propostas da agência.', TRUE
WHERE NOT EXISTS (SELECT 1 FROM cotacoes_propostas WHERE numero = 'PROP-2026-0001');

INSERT INTO cotacoes_propostas (
    numero, agencia, nome_cliente, cpf_cnpj, produto, modalidade, valor, status, prioridade,
    responsavel, matricula_responsavel, data_criacao, data_atualizacao, prazo_resposta, observacao, ativo
)
SELECT 'PROP-2026-0002', '1234', 'Cliente Demonstração 02', '11111111111', 'Habitação', 'Financiamento Habitacional',
       350000.00, 'PENDENTE_DOCUMENTACAO', 'ALTA', 'Gerente Agência', 'C000002',
       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, DATEADD('DAY', 5, CURRENT_DATE),
       'Aguardando complementação documental.', TRUE
WHERE NOT EXISTS (SELECT 1 FROM cotacoes_propostas WHERE numero = 'PROP-2026-0002');

INSERT INTO cotacoes_propostas (
    numero, agencia, nome_cliente, cpf_cnpj, produto, modalidade, valor, status, prioridade,
    responsavel, matricula_responsavel, data_criacao, data_atualizacao, prazo_resposta, observacao, ativo
)
SELECT 'PROP-2026-0003', '5678', 'Empresa Demonstração LTDA', '22222222000100', 'Capital de Giro', 'Pessoa Jurídica',
       80000.00, 'APROVADA', 'MEDIA', 'Consultor PJ', 'C000003',
       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, DATEADD('DAY', 1, CURRENT_DATE),
       'Proposta aprovada para simulação do painel.', TRUE
WHERE NOT EXISTS (SELECT 1 FROM cotacoes_propostas WHERE numero = 'PROP-2026-0003');

INSERT INTO historico_proposta (proposta_id, status_anterior, status_novo, usuario, matricula_usuario, descricao, criado_em)
SELECT p.id, NULL, p.status, p.responsavel, p.matricula_responsavel, 'Registro inicial criado por carga de dados.', CURRENT_TIMESTAMP
FROM cotacoes_propostas p
WHERE NOT EXISTS (SELECT 1 FROM historico_proposta h WHERE h.proposta_id = p.id);
